library/book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('addbooks/', views.Add_book.as_view(), name="addbooks"),
    path('viewbooks/', views.ViewBooks.as_view(), name="viewbooks"),
    path('detail/<int:i>', views.Detail.as_view(), name='detail'),
    path('delete/<int:i>', views.Del.as_view(), name='delete'),
path('edit/<int:i>', views.Edit_book.as_view(), name="edit"),

]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # book app URLs (home page, etc.)
    path('', include(('book.urls', 'book'), namespace='book')),

    # user app URLs (login, register, logout)
    path('user/', include(('user.urls', 'user'), namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/user/urls.py
from django.urls import path
from . import views
from user.views import  Register

from .views import UserLogin,UserLogout

app_name = "user"

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
]

library/book/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=30)
    author=models.CharField(max_length=40)
    price=models.IntegerField()
    pages=models.IntegerField()
    language=models.CharField(max_length=40)
    image=models.ImageField(upload_to='images')

library/user/models.py
from django.db import models

# Create your models here.

library/book/forms.py
from django import forms
from book.models import Book




# class Add(forms.Form):
#     title=forms.CharField()
#     author=forms.CharField()
#     price=forms.IntegerField()
#     pages=forms.IntegerField()
#     language=forms.CharField()

class Add(forms.ModelForm): #all the forms are automatically called
    class Meta: #inner class used to define the structure of form.
        model=Book
        fields="__all__"

library/user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = ''


class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField()

library/book/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import Add

from book.models import Book


books = []

class Add_book(View):
    def get(self, request):
        form_instance = Add()
        return render(request, 'addbooks.html', {'form': form_instance})

    def post(self, request):
        form_instance = Add(request.POST,request.FILES)
        if form_instance.is_valid():
            form_instance.save()
            # title = form_instance.cleaned_data['title']
            # author = form_instance.cleaned_data['author']
            # price = form_instance.cleaned_data['price']
            # pages = form_instance.cleaned_data['pages']
            # language = form_instance.cleaned_data['language']
            # b=Book.objects.create(title=form_instance.cleaned_data['title'],author=form_instance.cleaned_data['author'],price=form_instance.cleaned_data['price'],pages=form_instance.cleaned_data['pages'],language=form_instance.cleaned_data['language'])
            # b.save()
            # books.append({
            #     'title': title,
            #     'author': author,
            #     'price': price,
            #     'pages': pages,
            #     'language': language,
            # })
            #
            #
            # return redirect('book:viewbooks')

        return render(request, 'addbooks.html', {'form': form_instance})


class ViewBooks(View):
    def get(self, request):
        b=Book.objects.all()
        context={"books":b}
        return render(request, 'viewbooks.html', {'books': b})

class Detail(View):
    def get(self,request,i):
        print(i)
        b=Book.objects.get(id=i)
        context={'book':b}

        return render(request,'detail.html',context)
class Del(View):
    def get(self, request, i):
        b = Book.objects.get(id=i)
        b.delete()
        return redirect('book:viewbooks')

class Edit_book(View):
    def post(self,request,i):
        b = Book.objects.get(id=i)
        form_instance = Add(request.POST, request.FILES,instance=b)
        if form_instance.is_valid():
            form_instance.save()
            return redirect('book:viewbooks')


    def get(self,request,i):
        b=Book.objects.get(id=i)
        form_instance=Add(instance=b)
        context={'form':form_instance}
        return render(request,'edit.html',context)
# book/views.py
from django.views.generic import TemplateView

class Home(View):
    def get(self,request):
     return render(request, 'homepage.html')

library/user/views.py
from django.shortcuts import render
from django.views import View
from user.forms import RegisterForm , LoginForm
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
# Create your views here.
class Register(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, 'register.html', {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()  # automatically hashes password
            messages.success(request, "Registration successful! Please log in.")
            return redirect('user:login')  # include namespace
        return render(request, 'register.html', {'form': form})



class UserLogin(View):
    def post(self,request):
        form_instance=LoginForm(request.POST)
        if form_instance.is_valid():
            data=form_instance.cleaned_data
            u=data['username']
            p=data['password']
            user=authenticate(username=u,password=p)
            if user:
                login(request,user)
                return redirect('book:viewbooks')
            else:
                #print("invalid user")
                messages.error(request, "error logging in, kindly signup")
                return redirect('user:login')
    def get(self, request):
        form_instance=LoginForm()
        context={'form':form_instance}
        return render(request, 'login.html',context)


class UserLogout(View):
    def get(self, request):
        logout(request)
        return redirect('book:home')

library/templates/addbooks.html
{% extends 'home.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5 w-50">
    <h2 class="text-center mb-4">Add Book</h2>

    <form method="POST" class="border p-4 rounded shadow-sm" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form |crispy }}
        <button type="submit" class="btn btn-primary w-100 mt-3">Submit</button>
    </form>
</div>
{% endblock %}

library/templates/detail.html
{% extends 'home.html' %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Book Details</h2>

    <table class="table table-bordered w-50 mx-auto border-dark ">
        <tr>
            <th>Title</th>
            <td>{{ book.title }}</td>
        </tr>
        <tr>
            <th>Author</th>
            <td>{{ book.author }}</td>
        </tr>
        <tr>
            <th>Pages</th>
            <td>{{ book.pages }}</td>
        </tr>
        <tr>
            <th>Price</th>
            <td>{{ book.price }}</td>
        </tr>
        <tr>
            <th>Language</th>
            <td>{{book.language}}</td>
        </tr>
    </table>
</div>
{% endblock %}

library/templates/edit.html
{% extends 'home.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<h1>Edit book</h1>
 <form method="POST" class="border p-4 rounded shadow-sm" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form |crispy }}
        <button type="submit" class="btn btn-primary w-100 mt-3">Submit</button>
    </form>
{% endblock %}

library/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body class="bg-warning">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent ">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'book:addbooks' %}">Add_book</a>
        </li>
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'book:viewbooks' %}">View Book</a>
          </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'user:logout' %}">logout</a>
        </li>
          {% else %}
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'user:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'user:login' %}">login</a>
        </li>

          {% endif %}
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
          </ul>
    </div>
  </div>
</nav>


{% block content %}
{% endblock %}



</body>
</html>

library/templates/homepage.html
{% extends 'home.html' %}
{% block content %}
<h1> welcome to homepage</h1>
{% endblock %}

library/templates/login.html
{% extends 'home.html' %}
{% block content %}
<div class="container mt-5" style="max-width: 400px;">
  <h3 class="text-center mb-4">Login</h3>

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} text-center">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  <form method="POST" action="{% url 'user:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary w-100 mt-2">Login</button>
  </form>
{% endblock %}

library/templates/register.html
{% extends 'home.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-box">
  <h3>Register</h3>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success w-100 mt-2">Sign Up</button>
  </form>
</div>
{% endblock %}

library/templates/viewbooks.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">All Books</h2>
    <table class="table table-bordered">
    <tr>
        <th>cover photo</th>
        <th>Title</th>
        <th>Author</th>
        <th>Price</th>
        <th>Pages</th>
        <th>Language</th>
        <th>actions</th>
    </tr>

    {% for i in books %}
    <tr>
        <td><img src="{{ i.image.url }}" height="100px" width="100px">
        <td>{{ i.title }}</td>
        <td>{{ i.author }}</td>
        <td>{{ i.price }}</td>
        <td>{{ i.pages }}</td>
        <td>{{ i.language }}</td>
        <td><a class="btn btn-danger" href="{% url 'book:detail' i.id %}">Details</a>
            <a class="btn btn-danger" href="{% url 'book:edit' i.id %}" >Edit</a>
            <a class="btn btn-danger" href="{% url 'book:delete' i.id %}">Delete</a></td>

    </tr>
    {% endfor %}
</table>

</div>
{% endblock %}