library123/book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path('', views.Add_book.as_view(), name="home"),
    path('addbooks/', views.Add_book.as_view(), name="addbooks"),
    path('viewbooks/', views.ViewBooks.as_view(), name="viewbooks"),
    path('detail/<int:i>', views.Detail.as_view(), name='detail'),
    path('delete/<int:i>', views.Del.as_view(), name='delete'),
path('edit/<int:i>', views.Edit_book.as_view(), name="edit"),

]

library123/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),   # handles book app
    path('user/', include('user.urls')),  # handles user app
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library123/user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
]

library123/book/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=30)
    author=models.CharField(max_length=40)
    price=models.IntegerField(max_length=40)
    pages=models.IntegerField(max_length=20)
    language=models.CharField(max_length=40)
    image=models.ImageField(upload_to='images')

library123/user/models.py
from django.db import models

# Create your models here.

library123/book/forms.py
from django import forms
from book.models import Book




# class Add(forms.Form):
#     title=forms.CharField()
#     author=forms.CharField()
#     price=forms.IntegerField()
#     pages=forms.IntegerField()
#     language=forms.CharField()

class Add(forms.ModelForm): #all the forms are automatically called
    class Meta: #inner class used to define the structure of form.
        model=Book
        fields="__all__"

library123/book/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import Add

from book.models import Book


books = []

class Add_book(View):
    def get(self, request):
        form_instance = Add()
        return render(request, 'addbooks.html', {'form': form_instance})

    def post(self, request):
        form_instance = Add(request.POST,request.FILES)
        if form_instance.is_valid():
            form_instance.save()
            # title = form_instance.cleaned_data['title']
            # author = form_instance.cleaned_data['author']
            # price = form_instance.cleaned_data['price']
            # pages = form_instance.cleaned_data['pages']
            # language = form_instance.cleaned_data['language']
            # b=Book.objects.create(title=form_instance.cleaned_data['title'],author=form_instance.cleaned_data['author'],price=form_instance.cleaned_data['price'],pages=form_instance.cleaned_data['pages'],language=form_instance.cleaned_data['language'])
            # b.save()
            # books.append({
            #     'title': title,
            #     'author': author,
            #     'price': price,
            #     'pages': pages,
            #     'language': language,
            # })
            #
            #
            # return redirect('book:viewbooks')

        return render(request, 'addbooks.html', {'form': form_instance})


class ViewBooks(View):
    def get(self, request):
        b=Book.objects.all()
        context={"books":b}
        return render(request, 'viewbooks.html', {'books': b})

class Detail(View):
    def get(self,request,i):
        print(i)
        b=Book.objects.get(id=i)
        context={'book':b}

        return render(request,'detail.html',context)
class Del(View):
    def get(self, request, i):
        b = Book.objects.get(id=i)
        b.delete()
        return redirect('book:viewbooks')

class Edit_book(View):
    def post(self,request,i):
        b = Book.objects.get(id=i)
        form_instance = Add(request.POST, request.FILES,instance=b)
        if form_instance.is_valid():
            form_instance.save()
            return redirect('book:viewbooks')


    def get(self,request,i):
        b=Book.objects.get(id=i)
        form_instance=Add(instance=b)
        context={'form':form_instance}
        return render(request,'edit.html',context)

library123/user/views.py
from django.shortcuts import render

# Create your views here.
def register(request):
    return render(request,'register.html')

def login(request):
    return render(request,'login.html')

library123/templates/addbooks.html
{% extends 'home.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5 w-50">
    <h2 class="text-center mb-4">Add Book</h2>

    <form method="POST" class="border p-4 rounded shadow-sm" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form |crispy }}
        <button type="submit" class="btn btn-primary w-100 mt-3">Submit</button>
    </form>
</div>
{% endblock %}

library123/templates/detail.html
{% extends 'home.html' %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Book Details</h2>

    <table class="table table-bordered w-50 mx-auto border-dark ">
        <tr>
            <th>Title</th>
            <td>{{ book.title }}</td>
        </tr>
        <tr>
            <th>Author</th>
            <td>{{ book.author }}</td>
        </tr>
        <tr>
            <th>Pages</th>
            <td>{{ book.pages }}</td>
        </tr>
        <tr>
            <th>Price</th>
            <td>{{ book.price }}</td>
        </tr>
        <tr>
            <th>Language</th>
            <td>{{book.language}}</td>
        </tr>
    </table>
</div>
{% endblock %}

library123/templates/edit.html
{% extends 'home.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<h1>Edit book</h1>
 <form method="POST" class="border p-4 rounded shadow-sm" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form |crispy }}
        <button type="submit" class="btn btn-primary w-100 mt-3">Submit</button>
    </form>
{% endblock %}

library123/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body class="bg-warning">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent ">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'book:addbooks' %}">Add_book</a>
        </li>
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'book:viewbooks' %}">View Book</a>
          </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'user:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'user:login' %}">login</a>
        </li>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
          </ul>
    </div>
  </div>
</nav>


{% block content %}
{% endblock %}



</body>
</html>

library123/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<h1> login</h1>

</body>
</html>

library123/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> Register</h1>

</body>
</html>

library123/templates/viewbooks.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">All Books</h2>
    <table class="table table-bordered">
    <tr>
        <th>cover photo</th>
        <th>Title</th>
        <th>Author</th>
        <th>Price</th>
        <th>Pages</th>
        <th>Language</th>
        <th>actions</th>
    </tr>

    {% for i in books %}
    <tr>
        <td><img src="{{ i.image.url }}" height="100px" width="100px">
        <td>{{ i.title }}</td>
        <td>{{ i.author }}</td>
        <td>{{ i.price }}</td>
        <td>{{ i.pages }}</td>
        <td>{{ i.language }}</td>
        <td><a class="btn btn-danger" href="{% url 'book:detail' i.id %}">Details</a>
            <a class="btn btn-danger" href="{% url 'book:edit' i.id %}" >Edit</a>
            <a class="btn btn-danger" href="{% url 'book:delete' i.id %}">Delete</a></td>

    </tr>
    {% endfor %}
</table>

</div>
{% endblock %}